# Elige un tema de Jekyll soportado por GitHub Pages
theme: jekyll-theme-modernist

# Título y descripción de tu sitio
title: Mi pagina web
description: En esta pagina encontraras proyectos tanto de software como de hardware.
